wso2/docker-mg

dockerfiles/alpine/mg/Dockerfile
dockerfiles/ubuntu/mg/Dockerfile

- Upgrade jdk to 8u265
- Upgrade ubuntu variant base to 20.04
Fixes #4 
Not Tested
---

Upgrade base OS and jdk

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

This causes security concerns for users. Since we don't use any untrusted servers removed the no-check prama from wget
Fixes #6 
Mac
---

Remove no-check-cert param

---

dockerfiles/alpine/mg/Dockerfile
dockerfiles/ubuntu/mg/Dockerfile

Fixes #9 
Mac Docker for desktop 3.2.2
---

Add pkg upgrade to build process

---

CHANGELOG.md

Update changelog for 3.2.1.2

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

Upgrade MG version to 3.2.3
Not Tested
---

upgrade MG version 3.2.3

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

Upgrade MG release 3.2.3
Not Tested
---

Upgrade MG release version to 3.2.3

---

dockerfiles/alpine/mg/Dockerfile
dockerfiles/ubuntu/mg/Dockerfile

$Subject
- https://github.com/wso2/docker-mg/issues/17

Upgrade jre and alpine version

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

As $subject, this will upgrade MG version to 3.2.4
Fixes #18

Upgrade MG version to 3.2.4

---

dockerfiles/alpine/mg/Dockerfile
dockerfiles/ubuntu/mg/Dockerfile

Change internal jdk path

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/ubuntu/mg/Dockerfile

Prepare for 3.2.4.2

---

dockerfiles/alpine/mg/Dockerfile

Change alpine dependencies

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

Fixes https://github.com/wso2/docker-mg/issues/33

Upgrade MG version to 3.2.6

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

This will upgrade MG version to 3.2.7
Fixes #35

Upgrade to MG 3.2.7

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

This will upgrade MG version to 3.2.7
Fixes #35

Upgrade MG version to 3.2.7

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

- Upgrade MGW version to 3.2.8
- Upgrade Ubuntu version to 22.04
- Upgrade JRE version to 8u382b05
Fixes https://github.com/wso2/docker-mg/issues/38
Fixes https://github.com/wso2/docker-mg/issues/39
Fixes https://github.com/wso2/docker-mg/issues/40
---

[3.2.x] Upgrade MGW version to 3.2.8

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

- Upgrade MGW version to 3.2.8
- Upgrade Ubuntu version to 22.04
- Upgrade JRE version to 8u382b05
Fixes https://github.com/wso2/docker-mg/issues/38
Fixes https://github.com/wso2/docker-mg/issues/39
Fixes https://github.com/wso2/docker-mg/issues/40
---

Upgrade MGW version to 3.2.8

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/ubuntu/mg/Dockerfile

Upgrade Alpine version and remove unnecessary packages.
Fixes https://github.com/wso2/docker-mg/issues/43
Tested in Mac with Docker 24.0.6-rd
---

Upgrade Alpine version and remove unnecessary packages

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/ubuntu/mg/Dockerfile

Upgrade to API Microgateway 3.2.9
Fixes #46

Upgrade to API Microgateway 3.2.9

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile

This will upgrade the alpine base image
Fixes #48

Upgrade alpine base image

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

New docker release v3.2.9.3

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

JDK 17 Upgrade & New docker release v3.2.9.3 

---

CHANGELOG.md
dockerfiles/alpine/mg/Dockerfile
dockerfiles/alpine/mg/README.md
dockerfiles/ubuntu/mg/Dockerfile
dockerfiles/ubuntu/mg/README.md

$subject.
Fixes https://github.com/wso2/docker-mg/issues/59

Add 3.2.10 runtime
